base-config:
  company: Cohere
  open_source: false
  documentation_url: https://docs.cohere.com/v2/docs/models
  supports:
    images: false
    files: false
    tools: true
  properties:
    reasoning_model: false
    training_cutoff: null

command-a-plus-models:
  cohere/command-a-plus-05-2026:
    label: Command A+
    release_date: 2026-05-20
    open_source: true
    documentation_url: https://docs.cohere.com/docs/command-a-plus
    supports:
      images: true
      temperature: true
    properties:
      context_window: 128_000
      max_tokens: 64_000
      reasoning_model: true
      training_cutoff: "2025-04-01"
    costs_per_million_token: null
    default_parameters:
      temperature: 0.9
      top_p: 0.95

north-mini-code-models:
  cohere/north-mini-code-1-0:
    label: North Mini Code
    release_date: 2026-06-09
    open_source: true
    supports:
      temperature: true
    properties:
      context_window: 256_000
      max_tokens: 64_000
      reasoning_model: true
      training_cutoff: null
    costs_per_million_token: null
    default_parameters:
      temperature: 1
      top_p: 0.95

command-models:
  base-config:
    supports:
      temperature: true
    default_parameters:
      temperature: 0.3

  cohere/command-a-03-2025:
    label: Command A
    release_date: 2025-03-13
    properties:
      context_window: 256000
      max_tokens: 8000
    costs_per_million_token:
      input: 2.5
      output: 10.0

  cohere/command-r7b-12-2024:
    label: Command R7B
    release_date: 2024-12-13
    properties:
      context_window: 128000
      max_tokens: 4000
    costs_per_million_token:
      input: 0.0375
      output: 0.15
