base-config:
  company: zAI
  country: China
  open_source: true
  documentation_url: https://docs.z.ai/
  supports:
    images: false
    videos: false
    files: false
    batch: false
    temperature: true
    tools: true
    output_schema: false
  properties:
    reasoning_model: true

glm-models:
  zai/glm-5.3-flash:
    label: GLM 5.3 Flash
    release_date: 2026-08-26
    documentation_url: https://docs.z.ai/guides/vlm/glm-5.3-flash
    supports:
      images: true
    properties:
      context_window: 1_000_000
      max_tokens: 128_000
    provider_properties:
      clear_thinking: false
      supports_disabling_thinking: false
      international: true
    default_parameters:
      temperature: 1.0
      top_p: 0.95
      reasoning_effort: max
    costs_per_million_token:
      input: 0.075
      output: 0.25
      cache:
        read: 0.015
    provider_endpoint: glm-5.3-flash

  zai/glm-5.3:
    label: GLM 5.3
    release_date: 2026-08-18
    properties:
      context_window: 1_000_000
      max_tokens: 128_000
    provider_properties:
      clear_thinking: false
      supports_disabling_thinking: false
      international: true
    default_parameters:
      temperature: 1.0
      top_p: 0.95
      reasoning_effort: max
    costs_per_million_token:
      input: 1.4
      output: 4.4
      cache:
        read: 0.26
    provider_endpoint: glm-5.3
